[colors]
background = #202020
foreground = #9b8d7f
focused-bg = #9b8d7f
focused-fg = #202020

[bar/main]
width = 100%
height = 25
position = bottom
background = ${colors.background}
foreground = ${colors.foreground}
font-0 = "Iosevka Nerd Font:size=12;2"
padding-left = 0
padding-right = 0
module-margin = 0

modules-left = i3
modules-center = xwindow
modules-right = tray cpu volume memory battery date 

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true

label-focused = %name%
label-focused-background = ${colors.focused-bg}
label-focused-foreground = ${colors.focused-fg}
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-padding = 1

label-visible = %name%
label-visible-padding = 1

label-urgent = %name%
label-urgent-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%

[module/tray]
type = internal/tray
tray-spacing = 2

[module/cpu]
type = internal/cpu
interval = 1
format = cpu <label>% ::
label = %percentage%
format-padding = 1

[module/memory]
type = internal/memory
interval = 1
format = mem <label>% ::
label = %percentage_used%
format-padding = 1

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
format-charging = bat <label-charging>% ::
format-discharging = bat <label-discharging>% ::
format-full = bat <label-full>% ::
label-charging = %percentage%
label-discharging = %percentage%
label-full = %percentage%
format-padding = 1
; [module/network]
; type = internal/network
; interface = wlan0
; interval = 5
; format-connected = wifi <label-connected>
; format-disconnected = no network
; label-connected = %essid%

[module/volume]
type = internal/pulseaudio
format-volume = vol <label-volume>%
format-muted = vol muted
label-volume = %percentage%
click-right = pavucontrol
interval = 1
format-padding = 1
[module/date]
type = internal/date
interval = 1
date = %a %d %b
time = %I:%M:%S
label = %date% %time%
format-padding = 1

[module/separator]
type = custom/text
interval = 1
content =::
content-foreground = ${colors.foreground}
format-padding = 1